// Original integration fixture; models are generated by Xpeng/moonthrift 0.2.0.
struct Record {
  1: required i64 id,
  2: optional string label,
  3: optional map<string, list<i64>> series
}
exception Problem { 1: required string message }
service Shared {
  i64 add(1: i64 a, 2: i64 b),
  Record echo(1: Record record),
  binary blob(1: binary data),
  void fail() throws (1: Problem problem),
  oneway void notify(1: string text),
  string slow(1: i32 delayMs)
}
