///|
pub extend Problem with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Problem with Eq::{not_equal, equal}

///|
pub extend Record with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend Record with Eq::{not_equal, equal}

///|
pub extend SharedAddArgs with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SharedAddArgs with Eq::{not_equal, equal}

///|
pub extend SharedAddResult with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SharedAddResult with Eq::{not_equal, equal}

///|
pub extend SharedBlobArgs with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SharedBlobArgs with Eq::{not_equal, equal}

///|
pub extend SharedBlobResult with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SharedBlobResult with Eq::{not_equal, equal}

///|
pub extend SharedEchoArgs with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SharedEchoArgs with Eq::{not_equal, equal}

///|
pub extend SharedEchoResult with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SharedEchoResult with Eq::{not_equal, equal}

///|
pub extend SharedFailResult with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SharedFailResult with Eq::{not_equal, equal}

///|
pub extend SharedNotifyArgs with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SharedNotifyArgs with Eq::{not_equal, equal}

///|
pub extend SharedNotifyResult with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SharedNotifyResult with Eq::{not_equal, equal}

///|
pub extend SharedSlowArgs with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SharedSlowArgs with Eq::{not_equal, equal}

///|
pub extend SharedSlowResult with @moonbitlang/core/debug.Debug::{to_repr}

///|
pub extend SharedSlowResult with Eq::{not_equal, equal}
